name: SFFL Beat Reporter (Realtime)

on:
  schedule:
    - cron: "*/25 * * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run realtime
        env:
          SLEEPER_LEAGUE_ID: ${{ secrets.SLEEPER_LEAGUE_ID }}
          BSKY_HANDLE: ${{ secrets.BSKY_HANDLE }}
          BSKY_APP_PASSWORD: ${{ secrets.BSKY_APP_PASSWORD }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_GIST_ID: ${{ secrets.GH_GIST_ID }}
          DRY_RUN: "0"
          DEBUG: "0"
        run: python sffl_bsky_realtime.py
