name: SFFL Daily Digest (8am ET)

on:
  schedule:
    - cron: "0 12 * * *"   # 08:00 ET during EDT
    - cron: "0 13 * * *"   # 08:00 ET during EST
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run daily digest
        env:
          SLEEPER_LEAGUE_ID: ${{ secrets.SLEEPER_LEAGUE_ID }}
          BSKY_HANDLE: ${{ secrets.BSKY_HANDLE }}
          BSKY_APP_PASSWORD: ${{ secrets.BSKY_APP_PASSWORD }}
          DRY_RUN: "0"
          DEBUG: "0"
        run: python sffl_bsky_daily.py
